class TokenType
	INTEGER = :INTEGER
	FLOAT = :FLOAT
	BINARYOPERATOR = :BINARYOPERATOR
	IDENTIFIER = :IDENTIFIER
	RESERVED = :RESERVED
	LPAREN = :LPAREN
	RPAREN = :RPAREN
	EOF = :EOF
end

class Operators
	PLUS = :+
	MINUS = :-
	MULTIPLY = :*
	DIVIDE = :/
end