class TokenType
	INTEGER = :INTEGER
	FLOAT = :FLOAT
	OPERATOR = :OPERATOR
	LPAREN = :LPAREN
	RPAREN = :RPAREN
	EOF = :EOF
end

class Operators
	PLUS = :PLUS
	MINUS = :MINUS
	MULTIPLY = :MULTIPLY
	DIVIDE = :DIVIDE
end