# Class for representing a token generated by the lexer
class Token
    attr_reader :type, :value, :line, :column

    def initialize(type, value, line, column)
        @type = type
        @value = value
        @line = line
        @column = column
    end
     
    # Convert the object to a string representation
    # @return String - The object converted to string
    def to_s()
        return "#{self.type}: #{self.value}, (#{@line}, #{@column})"
    end
end