# Class for representing a token generated by the lexer
class Token
  attr_reader :type, :value, :position

  #
  # Create a token
  #
  # @param [Symbol] type What type of token this is
  # @param [String] value The value of the token
  # @param [Integer] line At what line the token begins at
  # @param [Integer] column At what column the token begins at
  #
  def initialize(type, value, position)
    @type = type
    @value = value
    @position = position
  end

  # Convert the object to a string representation
  #
  # @return [String] The object converted to string
  def to_s
    "#{type}: #{value}, (#{position.line_nr}, #{position.column})"
  end
end
